# Generated by Django 5.1.1 on 2024-10-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studforce_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="usage_limit",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="promotion",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
